# Generated by Django 6.1.1 on 2026-09-30 06:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('asunto', models.CharField(max_length=150, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'db_table': 'contacto',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Personaje')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Personaje',
                'verbose_name_plural': 'Personajes',
                'db_table': 'personaje',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la Receta')),
                ('tipo', models.CharField(choices=[('s', 'Salada'), ('p', 'Postre')], default='s', max_length=1)),
                ('imagen', models.CharField(max_length=150, verbose_name='Imagen (ruta dentro de static)')),
                ('alt', models.CharField(max_length=200, verbose_name='Texto alternativo de la imagen')),
                ('ingredientes', models.TextField(verbose_name='Ingredientes (JSON)')),
                ('preparacion', models.TextField(verbose_name='Preparación (JSON)')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden en la página')),
                ('orden_carrusel', models.PositiveSmallIntegerField(default=0, verbose_name='Posición en el carrusel (0 = no aparece)')),
                ('nueva', models.BooleanField(default=False, verbose_name='Mostrar en "Nuevas Recetas Añadidas"')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'db_table': 'receta',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, verbose_name='Código SKU')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('tamano', models.CharField(choices=[('p', 'Pequeño (Llavero)'), ('m', 'Mediano (Peluche normal)'), ('g', 'Grande (Cojín)')], default='m', max_length=1)),
                ('precio', models.PositiveIntegerField(default=10000, verbose_name='Precio')),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Lanzamiento')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tiendaApp.categoria')),
                ('personaje', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tiendaApp.personaje')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['personaje', 'nombre'],
            },
        ),
    ]
